project/cliente/urls.py
from django.urls import path

from . import views

app_name = "cliente"

urlpatterns = [
path("", views.index, name="index"),
path("crear/", views.crear,name= "crear"),
]

project/comentario/urls.py
from django.urls import path

from . import views

app_name = "comentario"

urlpatterns = [
path("", views.index, name="index"),
path("exito_comentario/",views.exito_comentario, name= "exito_comentario")
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
path ("", include("home.urls")),
path("cliente/", include("cliente.urls")),
path("comentario/", include("comentario.urls"))


]

project/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
path("", views.index, name="index"),
path("about/", views.about, name="about"),
]

project/cliente/models.py
from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self) -> str:
        return self.nombre

class Cliente(models.Model):
     nombre = models.CharField(max_length=100)
     apellido = models.CharField(max_length=100)
     nacimiento = models.DateField(null=True)
     pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True)

     def __str__(self) -> str:
      return f"{self.nombre} {self.apellido}"

project/comentario/models.py
from django.db import models

class Comentario(models.Model):
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.texto

# Create your models here.

project/compraventa/models.py
from django.db import models

# Create your models here.

project/cliente/forms.py
from django import forms
from . import  models

class clienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = ["nombre","apellido","nacimiento","pais_origen_id"]

project/comentario/forms.py
from django import forms
from .models import Comentario

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']

project/cliente/views.py
from django.shortcuts import render,redirect
from . import models
from . import forms

def index(request):
     clientes = models.Cliente.objects.all()

     return render(request,"cliente/index.html", {"clientes": clientes})

def crear(request):
     if request.method == "POST":
          form = forms.clienteForm(request.POST)
          if form.is_valid():
               form.save()
               return redirect("cliente:index")
     else:
          form = forms.clienteForm()
     return render(request, "cliente/crear.html",{"form":form})


# Create your views here.

project/comentario/views.py
from django.shortcuts import render, redirect
from .models import Comentario
from .forms import ComentarioForm

def index(request):
    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('comentario:exito_comentario')
    else:
        form = ComentarioForm()
    
    comentarios = Comentario.objects.all()
    
    return render(request, 'comentario/index.html', {'form': form, 'comentarios': comentarios})

def exito_comentario(request):
    return render(request, 'comentario/exito_comentario.html')


# Create your views here.

project/compraventa/views.py
from django.shortcuts import render

# Create your views here.

project/home/views.py
from django.shortcuts import render

def index(request):
    return render(request, "home/index.html")

def about(request):
    return render(request,"home/about.html")

# Create your views here.

project/cliente/templates/cliente/crear.html
{% extends 'home/base.html' %}

{% block title %}
<h2>Crear cliente</h2>   
{% endblock title %}

{% block content %}

<form action=""method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>

<p><a href="{% url 'home:index' %}">ir atras</a></p>


{% endblock content %}

project/cliente/templates/cliente/index.html
{% extends 'home/base.html' %}

{% block title %}

<h2>Clientes</h2>
    
{% endblock title %}

{% block content %}
    <ul>
        {% for cliente in clientes %}
            <li>{{ cliente.nombre }} {{ cliente.apellido }}</li>
        {% endfor %}
    </ul>


    <p><a href="{% url 'cliente:crear' %}">crear cliente</a></p>
    <p><a href="{% url 'home:index' %}">Ir atras</a></p>
    
{% endblock content %}

project/comentario/templates/comentario/exito_comentario.html
{% extends 'home/base.html' %}

{% block title %}
    <h2>Comentarios</h2>
{% endblock title %}

{% block content %}

    <h2>Comentario Agregado con Éxito</h2>
    <p>Tu comentario se ha agregado con éxito.</p>
    <p><a href="{% url 'comentario:index' %}">Volver a la página de comentarios</a></p>
  
{% endblock content %}

project/comentario/templates/comentario/index.html
{% extends 'home/base.html' %}

{% block title %}
    <h2>Agregar Comentarios</h2>
{% endblock title %}

{% block content %}
    <h3>Agregar un nuevo comentario:</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Comentar</button>
    </form>

    <h3>Comentarios existentes:</h3>
    {% for comentario in comentarios %}
        <p>{{ comentario.text }}</p>
        <small>{{ comentario.date_added }}</small>
    {% empty %}
        <p>No hay comentarios aún.</p>
    {% endfor %}

    <p><a href="{% url 'home:index' %}">Ir atrás</a></p>
{% endblock content %}

project/home/templates/home/about.html
{% extends 'home/base.html' %}
{% block title %}
    <h2>Quienes somos?</h2>
{% endblock title %}

{% block content %}
    <p>una paguina para que puedas vender y comprar camisetas de futboll</p>
    <button><a href="{% url 'home:index' %}">Ir atras</a></button>
{% endblock content %}

project/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>CASACA Tienda</h1>
    
    {% block title %}   
    {% endblock title %}

    {% block content %}
    {% endblock content %}

    
</body>
</html>

project/home/templates/home/index.html
{% extends 'home/base.html' %}

{% block title %}
    <h2>HOME</h2>
{% endblock title %}
    
{% block content %}
    <p><a href="{% url 'cliente:crear' %}">Crear Clientes</a></p>
    <p><a href="{% url 'comentario:index' %}">Comentarios</a></p>
    <p><a href="">vender</a></p>
    <p><a href="{% url 'cliente:index' %}">Clientes</a></p>
    <p><a href="{% url 'home:about' %}">Quienes somos ?</a></p>  
{% endblock content %}